---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kafdrop
  namespace: strimzi-kafka-poc
spec:
  url: https://lsst-sqre.github.io/charts/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafdrop
spec:
  releaseName: kafdrop
  interval: 1m
  chart:
    spec:
      chart: kafdrop
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: kafdrop
        namespace: strimzi-kafka-poc
  values:
    image:
      repository: docker.io/obsidiandynamics/kafdrop
      tag: "3.29.0"

    kafka:
      brokerConnect: "strimzi-kafka-poc-minimal-ephemeral-kafka-bootstrap.strimzi-kafka-poc.svc.cluster.local:9092"
