---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kafka
  namespace: strimzi-kafka-poc
spec:
  url: https://strimzi.io/charts/
  interval: 10m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-operator
spec:
  releaseName: kafka-operator
  interval: 1m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.28.0"
      sourceRef:
        kind: HelmRepository
        name: kafka
        namespace: strimzi-kafka-poc
  values:
    image:
      repository: strimzi
      name: operator
      tag: 0.28.0